version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform123
    ports:
      - "5434:5432"  # Mapear porta externa 5434 para interna 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6370:6379"  # Mapear porta externa 6370 para interna 6379
    restart: unless-stopped

volumes:
  postgres_data:
